### ISSUE TITLE
audio(error): alSourcef(_source,AL_GAIN): Invalid Value

### ISSUE THREAD

**Issue by CosmoTheFakeMOD** [Toontown-Offline-Issue-Tracker/issues#10]
When playing "**Target**" minigame, the log is flooded with an error.
[ttoff-200706_014531.log](https://github.com/Toontown-Offline-Issue-Tracker/issues/files/4877736/ttoff-200706_014531.log)

**Comment by Benjamin8693** [comment]
This has been fixed :)
