### ISSUE TITLE
Crash due to Green Magic Word edge case

### ISSUE THREAD

**Issue by Benjamin8693** [Toontown-Offline-Issue-Tracker/issues#13]
Only just skimmed this log, but may be an issue with greening a Toon with themselves while they're in a cog disguise.
[ttoff-200622_012016-1.log](https://github.com/Toontown-Offline-Issue-Tracker/issues/files/4878362/ttoff-200622_012016-1.log)

**Comment by ooowoothevirtualhowler** [comment]
Yet more cases of Toon vs. DistributedToon. Actually now that I read this it looks like it's because the method isn't called and it's declared like a variable lol

**Comment by ooowoothevirtualhowler** [comment]
All done and it should work with NPCs now too.
