### ISSUE TITLE
Fisherman Freddy shadow is misplaced

### ISSUE THREAD

**Issue by CosmoTheFakeMOD** [Toontown-Offline-Issue-Tracker/issues#25]
![image](https://user-images.githubusercontent.com/67851237/86753844-4395b980-bff5-11ea-8b3d-c85ba8111f1a.png)

Shadow is on his shoulders

**EDIT: I notice this occurs to all fisherman in all playgrounds**

**Comment by Benjamin8693** [comment]
Made a bit of progress on diagnosing the issue. Upon initially loading in to a playground, the shadow will be messed up. If you go from playground to playground, it will remain messed up.

For example, TTC>DD>TTC won't fix anything.

However, going into an interior then coming back out to the playground will fix the issue and shadows will appear as normal. They will break again. after you leave the playground.

**Comment by Benjamin8693** [comment]
This has been fixed by myself.
