### ISSUE TITLE
Crash when going to plan a Party /w holiday skybox enabled

### ISSUE THREAD

**Issue by Benjamin8693** [Toontown-Offline-Issue-Tracker/issues#26]
If you enable a Halloween holiday /w the halloween skybox and then go to plan a party, you will crash.
[ttoff-200707_192844.log](https://github.com/Toontown-Offline-Issue-Tracker/issues/files/4888246/ttoff-200707_192844.log)

**Comment by ooowoothevirtualhowler** [comment]
Looks simple to fix. It's literally just putting the file path for the sky inside PartyHood. Question is if we want to have holiday skies in parties because there's already the decorations that spawn custom skyboxes.

**Comment by ooowoothevirtualhowler** [comment]
Guess I'll just push it now and we'll decide later if we don't want parties to be affected by the Halloween holiday.
