### ISSUE TITLE
game crashed when doing skipmovie with lure and trap

### ISSUE THREAD

**Issue by CosmoTheFakeMOD** [Toontown-Offline-Issue-Tracker/issues#30]
I threw the TNT down and then i used a $10 bill to lure, but used skipmovie
I was in a cog building.

[ttoff-200710_011930.log](https://github.com/Toontown-Offline-Issue-Tracker/issues/files/4901907/ttoff-200710_011930.log)

**Comment by Benjamin8693** [comment]
This has been fixed by myself.
