### ISSUE TITLE
broken walking/running animation

### ISSUE THREAD

**Issue by CosmoTheFakeMOD** [Toontown-Offline-Issue-Tracker/issues#35]
When doing the easter egg to Dreamy Drive, your Toon is sliding around instead of walking or running animation.

**Comment by CosmoTheFakeMOD** [comment]
![image](https://user-images.githubusercontent.com/67851237/88372523-ec108100-cd4a-11ea-9bfa-02abb81ee62d.png)

So i guess this is why im sliding around at dreamy all the time.

**Comment by Benjamin8693** [comment]
May be fixed in v1.0.2.0

**Comment by CosmoTheFakeMOD** [comment]
Look like it's fixed.

**Comment by CosmoTheFakeMOD** [comment]
![image](https://user-images.githubusercontent.com/67851237/89095337-bc342f80-d381-11ea-9f84-6f22e07ef183.png)
 but i've noticed this when going to dreamy, after being greened by cog
