### ISSUE TITLE
game crashes when TPing to campsite

### ISSUE THREAD

**Issue by CosmoTheFakeMOD** [Toontown-Offline-Issue-Tracker/issues#9]
### _This bug only works if you're in the campsite and TP to the camp once again._

[ttoff-200706_010840.log](https://github.com/Toontown-Offline-Issue-Tracker/issues/files/4877981/ttoff-200706_010840.log)

**Comment by Benjamin8693** [comment]
Please provide the actual log file next time, not just a bunch of text taken from it.

**Comment by CosmoTheFakeMOD** [comment]
fixed the post

**Comment by Benjamin8693** [comment]
This has been fixed by @frozenstranger
