### ISSUE TITLE
Field Office walls are weirdly randomized

### ISSUE THREAD

**Issue by ProfMcMouse** [Toontown-Offline-Issue-Tracker/issues#93]
In this video from 2011, you can see the walls of the Field Office are random different walls.
![image](https://user-images.githubusercontent.com/27360239/94623925-38c58a80-02ad-11eb-990d-984c14b2df36.png)

However, a field office spawned in the same place has only two different walls.
![image](https://user-images.githubusercontent.com/27360239/94624117-a2de2f80-02ad-11eb-8859-9ec1b5c6732b.png)

While this could be a coincidence, spawning more Field Offices on the same street has the same types of walls constantly appearing.
![image](https://user-images.githubusercontent.com/27360239/94624194-c903cf80-02ad-11eb-80e1-c332a8527406.png)

After relogging a bunch of times, the types of walls changed, but they still don't look really random, and is still only using two types of walls
![image](https://user-images.githubusercontent.com/27360239/94625120-ea65bb00-02af-11eb-8163-0fe33a5abb14.png)

**Comment by Benjamin8693** [comment]
Fixed in v1.0.5.0
